name: transcribr
description: Rolling 30s audio segments with background recording
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  record: ^6.1.1
  path_provider: ^2.1.3
  permission_handler: ^12.0.1
  flutter_background_service: ^5.0.6
  flutter_background_service_android: ^6.2.2
  flutter_local_notifications: ^19.4.2
  http: ^1.2.2
  shared_preferences: ^2.3.2
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.2
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  web_socket_channel: ^3.0.1
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
