// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4rhemQJlJ63GB4jhRH0RSMD3l_sBjes0',
    appId: '1:228176257363:web:22d7387b49fa7c19cdc1a6',
    messagingSenderId: '228176257363',
    projectId: 'rolling-audio',
    authDomain: 'rolling-audio.firebaseapp.com',
    storageBucket: 'rolling-audio.firebasestorage.app',
    measurementId: 'G-LKXVFDDC7L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo8wvdsUbhmLVK5AVdtiGXM7xRTYM4J1U',
    appId: '1:228176257363:android:a635349cc9a6c053cdc1a6',
    messagingSenderId: '228176257363',
    projectId: 'rolling-audio',
    storageBucket: 'rolling-audio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGUnx9aDD2hyQvkE7Vtw3sn1yDWL3ibcg',
    appId: '1:228176257363:ios:2351065d99637a42cdc1a6',
    messagingSenderId: '228176257363',
    projectId: 'rolling-audio',
    storageBucket: 'rolling-audio.firebasestorage.app',
    iosBundleId: 'com.example.transcribrApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGUnx9aDD2hyQvkE7Vtw3sn1yDWL3ibcg',
    appId: '1:228176257363:ios:2351065d99637a42cdc1a6',
    messagingSenderId: '228176257363',
    projectId: 'rolling-audio',
    storageBucket: 'rolling-audio.firebasestorage.app',
    iosBundleId: 'com.example.transcribrApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4rhemQJlJ63GB4jhRH0RSMD3l_sBjes0',
    appId: '1:228176257363:web:a68cf168ebfd2fd8cdc1a6',
    messagingSenderId: '228176257363',
    projectId: 'rolling-audio',
    authDomain: 'rolling-audio.firebaseapp.com',
    storageBucket: 'rolling-audio.firebasestorage.app',
    measurementId: 'G-EEMX0RDRT4',
  );
}
